// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // New Firebase Project: gey-talk
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRVSkfj7BfxkjpQIQrHmgjobm-uEWUX1E',
    appId: '1:243169198439:web:927ee0ad134f1c08702fc2',
    messagingSenderId: '243169198439',
    projectId: 'gey-talk',
    storageBucket: 'gey-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRVSkfj7BfxkjpQIQrHmgjobm-uEWUX1E',
    appId: '1:243169198439:web:927ee0ad134f1c08702fc2',
    messagingSenderId: '243169198439',
    projectId: 'gey-talk',
    storageBucket: 'gey-talk.firebasestorage.app',
    iosBundleId: 'com.gumbotech.gaytalks',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRVSkfj7BfxkjpQIQrHmgjobm-uEWUX1E',
    appId: '1:243169198439:web:927ee0ad134f1c08702fc2',
    messagingSenderId: '243169198439',
    projectId: 'gey-talk',
    authDomain: 'gey-talk.firebaseapp.com',
    storageBucket: 'gey-talk.firebasestorage.app',
    measurementId: 'G-0MF05WB9FD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRVSkfj7BfxkjpQIQrHmgjobm-uEWUX1E',
    appId: '1:243169198439:web:927ee0ad134f1c08702fc2',
    messagingSenderId: '243169198439',
    projectId: 'gey-talk',
    storageBucket: 'gey-talk.firebasestorage.app',
    iosBundleId: 'com.gumbotech.gaytalks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRVSkfj7BfxkjpQIQrHmgjobm-uEWUX1E',
    appId: '1:243169198439:web:927ee0ad134f1c08702fc2',
    messagingSenderId: '243169198439',
    projectId: 'gey-talk',
    authDomain: 'gey-talk.firebaseapp.com',
    storageBucket: 'gey-talk.firebasestorage.app',
    measurementId: 'G-0MF05WB9FD',
  );
}